<?php

$json='{"records":{"person_id":"5f432bd9ab2b1","person_name":"Eduardo","person_lastname_paterno":"Peralta","person_lastname_materno":"Popoca","person_mail":"aeadsa@sdaas.com","person_phone":"876567653","person_birthday":"1966-01-04 04:51:58","person_smoker":"0","person_ocupation":"Ingeniero","person_civil_state":"1","person_spouse":"5f432bd9ab2b5","person_sons":"[\"5f432bd9ab2b7\",\"5f432bd9abea2\"]","person_type":"PROSPECTO","person_asma":"0","person_motociclismo":"0","person_diabetes":"0","person_hipertencion":"0","person_tiroides":"0","person_investment":"mensual","person_references":"[\"5f432bd9ac942\",\"5f432bd9ace12\",\"5f432bd9ad32c\",\"5f432bd9ad7ba\"]","person_deleted":"0","person_recomended_by":null,"person_data":"{\"name\":\"Eduardo\",\"lastname_materno\":\"Popoca\",\"lastname_paterno\":\"Peralta\",\"mail\":\"aeadsa@sdaas.com\",\"phone\":\"876567653\",\"birthday\":\"1966-01-04T03:51:58.155Z\",\"smoker\":false,\"ocupation\":\"Ingeniero\",\"civil_state\":true,\"spouse\":{\"name\":\"Carolina\",\"lastname_materno\":\"Romero\",\"lastname_paterno\":\"Fernandez\",\"mail\":\"sada@sdasd\",\"phone\":\"5554645645\",\"birthday\":\"\"},\"is_father\":true,\"sons\":[{\"name\":\"Frank\",\"lastname_materno\":\"Gomez\",\"lastname_paterno\":\"Serdan\",\"mail\":\"sdasd@asda.com\",\"phone\":\"4353535\",\"$$hashKey\":\"object:84\"},{\"name\":\"Frank\",\"lastname_materno\":\"Gomez\",\"lastname_paterno\":\"Serdan\",\"mail\":\"sdasd@asda.com\",\"phone\":\"4353535\",\"$$hashKey\":\"object:86\"}],\"asma\":false,\"motociclismo\":false,\"diabetes\":false,\"hipertencion\":false,\"tiroides\":false,\"investment\":\"mensual\",\"references\":[{\"name\":\"Edgardo\",\"lastname_materno\":\"asdasda\",\"lastname_paterno\":\"asdasda\",\"mail\":\"Refe@asda.com\",\"phone\":\"655645645\",\"$$hashKey\":\"object:88\"},{\"name\":\"Edgardo\",\"lastname_materno\":\"asdasda\",\"lastname_paterno\":\"asdasda\",\"mail\":\"Refe@asda.com\",\"phone\":\"655645645\",\"$$hashKey\":\"object:90\"},{\"name\":\"Edgardo\",\"lastname_materno\":\"asdasda\",\"lastname_paterno\":\"asdasda\",\"mail\":\"Refe@asda.com\",\"phone\":\"655645645\",\"$$hashKey\":\"object:92\"},{\"name\":\"Edgardo\",\"lastname_materno\":\"asdasda\",\"lastname_paterno\":\"asdasda\",\"mail\":\"Refe@asda.com\",\"phone\":\"655645645\",\"$$hashKey\":\"object:94\"}]}","person_history":null}}';
//echo $json;
$data= json_decode($json);

var_dump($data);
echo "<br>";
var_dump(get_object_vars($data->records));

?>